#!/bin/sh

set -e

case "$1" in
  purge)
    rm -r -f /etc/areca                          \
             /usr/sbin/arc_http                  \
             /usr/sbin/archttpsrv.conf           \
             /usr/share/areca-archttp-binary     \
             /usr/share/doc/areca-archttp-binary 1> /dev/null 2>&1
  ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
  ;;

  *)
    echo "The postrm script called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#
